### ISSUE TITLE
Filament Dryer Capability.

### ISSUE THREAD

**Issue by ppak10** [erogizer/FilamentCabinetForVoron#1]
I have a quick question on the filament drying capability of this mod.

Since the filament box is above the printer itself, did you find that **heating from the print bed would be adequate enough to dry out the filament?**

I am curious if this is the case as I'd like to include this modification to my printer for humidity sensitive materials such as ABS but could not find suitable filament dryer boxes that can house 6+ roll of filament when used in conjunction with ERCF.
  
Thanks!

**Comment by erogizer** [comment]
프린터를 사용하는 열로 충분히 건조는 됩니다스풀을 개별로 보관하는 형태보다는 성능은 떨어지고요65mm폭의 스풀은 빠듯하게 12개 까지 보관가능할거같은데현재 8개스풀을 내부에 넣고 상단에 ERCF V2 올리는 작업중입니다2024. 1. 5. 22:53, Peter Myung-Won Pak ***@***.***> 작성:﻿
I have a quick question on the filament drying capability of this mod.
Since the filament box is above the printer itself, did you find that heating from the print bed would be adequate enough to dry out the filament?
I am curious if this is the case as I'd like to include this modification to my printer for humidity sensitive materials such as ABS but could not find suitable filament dryer boxes that can house 6+ roll of filament when used in conjunction with ERCF.
Thanks!
